service: metadata
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  # General settings
  name: aws
  region: ap-northeast-1
  profile: ruckplus
  # General function settings
  runtime: nodejs18.x
  memorySize: 128
  architecture: x86_64
  environment:
    STAGE: '${sls:stage}'
    MORALIS_API_KEY: '${env:MORALIS_API_KEY}'
  # General api settings
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - '*'
      allowedMethods:
        - '*'

custom:
  serverless-offline:
    httpPort: 4000

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

functions:
  # BATCH
  saveNftTokenAddresses:
    handler: src/batch/saveNftTokenAddresses/index.handler
    events:
      - schedule:
          rate: 'cron(0 */3 * * ? *)'
          enabled: false

  saveNftCollectionBatch:
    handler: src/batch/saveNftCollectionBatch/index.handler
    events:
      - schedule:
          rate: 'cron(0 */1 * * ? *)'
          enabled: false

  # API
  generateNonceApi:
    handler: src/api/auth/nonce/generate/index.handler
    events:
      - httpApi:
          path: /api/auth/nonce/generate
          method: post

  getNftCollectionApi:
    handler: src/api/nft/collection/index.handler
    events:
      - httpApi:
          path: /api/nft/collection
          method: get

  listCollectionApi:
    handler: src/api/collection/list/index.handler
    events:
      - httpApi:
          path: /api/collection
          method: get

  createCollectionApi:
    handler: src/api/collection/store/index.handler
    events:
      - httpApi:
          path: /api/collection
          method: post

resources:
  Resources:
    Metadata:
      Type: 'AWS::RDS::DBInstance'
      Properties:
        AllocatedStorage: '5'
        DBInstanceClass: 'db.t2.micro'
        DBInstanceIdentifier: '${env:MYSQL_DATABASE}'
        Engine: 'MySQL'
        MasterUsername: '${env:MYSQL_ROOT_USER}'
        MasterUserPassword: '${env:MYSQL_ROOT_PASSWORD}'
        MultiAZ: false
